# -*- coding: utf-8 -*-
"""PROJECT-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9lbnwOlysf2dtOvhguBNebGxtIY_2RT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Combined12.csv")
print(data.head())

print(data.info())
print(data.isnull().sum())
data.fillna(data.mean(numeric_only=True), inplace=True)

plt.figure()

plt.plot(data.index, data['temp_mean(c)'])

plt.title("Temperature Trend Over Time")
plt.xlabel("Index")
plt.ylabel("Mean Temperature (c)")

plt.xticks(rotation=45)
plt.show()

season_data = data.groupby('normalized_label')['temp_mean(c)'].mean()

plt.figure()
season_data.plot(kind='bar')

plt.title("Average Mean Temperature by Normalized Label")
plt.xlabel("Normalized Label")
plt.ylabel("Mean Temperature (c)")

plt.show()

plt.figure()

plt.hist(data['temp_mean(c)'], bins=20)

plt.title("Temperature Distribution")
plt.xlabel("Mean Temperature (c)")
plt.ylabel("Frequency")

plt.show()

plt.figure()

plt.scatter(data['temp_mean(c)'], data['Pressure'])

plt.title("Mean Temperature vs Pressure")
plt.xlabel("Mean Temperature (c)")
plt.ylabel("Pressure")

plt.show()

season_counts = data['normalized_label'].value_counts()

plt.figure()

plt.pie(season_counts, labels=season_counts.index, autopct='%1.1f%%')

plt.title("Normalized Label Distribution")

plt.show()

print("Correlation Matrix")
print(data.corr())

data.to_csv("/content/drive/MyDrive/Colab Notebooks/Combined12.csv", index=False)

print("Final Processed Dataset Saved Successfully")

