# -*- coding: utf-8 -*-
"""PROJECT1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tlIsEYOTOCG_94WNCjDvVVw5QSlZWkDf
"""





import numpy as np

# Sample sales dataset: [OrderID, Quantity Sold, Unit Price]
sales_data = np.array([
    [1001, 10, 15.5],
    [1002, 5, 20.0],
    [1003, 8, 12.0],
    [1004, 15, 10.0],
    [1005, 7, 18.0],
    [1006, 12, 14.5],
    [1007, 6, 22.0],
    [1008, 9, 16.0]
])

print("Sales Dataset:\n", sales_data)

quantity = sales_data[:, 1]
unit_price = sales_data[:, 2]

revenue = quantity * unit_price

total_sales = np.sum(revenue)
average_sales = np.mean(revenue)

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)

print("First 3 Records:\n", sales_data[:3])
print("Last 2 Records:\n", sales_data[-2:])
print("Quantities Only:\n", sales_data[:, 1])

mean_sales = np.mean(revenue)
median_sales = np.median(revenue)
variance_sales = np.var(revenue)
std_dev_sales = np.std(revenue)

print("Mean Revenue:", mean_sales)
print("Median Revenue:", median_sales)
print("Variance:", variance_sales)
print("Standard Deviation:", std_dev_sales)

revenue_broadcast = sales_data[:, 1] * sales_data[:, 2]
print("Revenue using Broadcasting:\n", revenue_broadcast)

# Apply 10% discount and calculate new revenue
discounted_price = unit_price * 0.9
new_revenue = quantity * discounted_price

print("New Revenue after 10% Discount:\n", new_revenue)